name: 'retry action'
author : |
  Wandalen <wandalen@obox.systems>
  dmvict <dm.vict.kr@gmail.com>
branding:
  icon: 'activity'
  color: 'white'
description: 'Retries an Github Action step on failure'
inputs:
  action:
    description: 'Github action name. Should be defined action or command, not both.'
    required: false
  command:
    description: 'Command to run. Should be defined action or command, not both.'
    required: false
  with:
    description: 'An options map for Github action'
    required: false
  current_path:
    description: 'Setup working directory for the action. Works with only commands. Default is `github.workspace` path.'
    required: false
  env_context:
    description: 'Get env context. It is autooption to pass context `env` into an external action. Not documented in file `Readme.md`.'
    required: false
    default: '{}'
  github_context:
    description: 'Get github context. It is autooption to pass context `github` into an external action. Not documented in file `Readme.md`.'
    required: false
    default: ${{ toJSON( github ) }}
  job_context:
    description: 'Get job context. It is autooption to pass context `job` into an external action. Not documented in file `Readme.md`.'
    required: false
    default: ${{ toJSON( job ) }}
  matrix_context:
    description: 'Get matrix context. It is autooption to pass context `matrix` into an external action. Not documented in file `Readme.md`.'
    required: false
    default: ${{ toJSON( matrix ) }}
  attempt_limit:
    description: 'Number of attempts'
    required: false
    default: 2
  attempt_delay:
    description: 'A delay between attempts in ms'
    required: false
    default: 0
runs:
  using: 'node12'
  pre: 'src/Pre.js'
  main: 'src/Main.js'
  post: 'src/Post.js'
