name: 'wretry.action'
author : dmvict
description: 'Retries an Github Action step on failure'
inputs:
  action:
    description: 'Github action name'
    required: true
  with:
    description: 'An options map for Github action'
    required: false
  attempt_limit:
    description: 'Number of attempts'
    required: false
    default: 2
  attempt_delay:
    description: 'A delay between attempts'
    required: false
    default: 0
runs:
  using: 'node12'
  main: 'src/Index.js'
